#
# Basic settings.
#
url: http://anthonygore.com
# baseurl: ""
title: Anthony Gore
description: I blog about tech stuff.
avatar: /assets/img/avatar.jpg
# language: ja
language: en

#
# Icons
#
icons:
  rss: true
  email:
  github: anthonygore
  bitbucket:
  twitter: anthonygore
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: https://www.linkedin.com/in/anthonygore
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: http://stackoverflow.com/users/2278963/anthonygore
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-54538653-2 # e.g. UA-000000-01
disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 5
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: false   # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: http://anthonygore.com/assets/img/avatar.jpg
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jemoji
  - jekyll-paginate

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - _pages/about.md
